### ISSUE TITLE
Oversized UVs on newer imported models

### ISSUE THREAD

**Issue by ThePlayer14** [Talv/m3addon#10]
When importing a newer model from HOTS (like Valeera, Yrel), the UVs of meshes are like 10x the size of the texture image and it takes some time to rescale and relocate them into their places. 
Is there a solution for this issue?

**Comment by ThePlayer14** [comment]
![screen1](https://user-images.githubusercontent.com/24374531/62524979-e0c0fe80-b836-11e9-8365-881f5379e2a8.png)
![screen](https://user-images.githubusercontent.com/24374531/62524992-e74f7600-b836-11e9-8fdd-0bbf400ff855.png)

**Comment by ThePlayer14** [comment]
and the issue is present in the older versions too, I had similar experiences with the 2.79 importer as well.

**Comment by Talv** [comment]
Yeah, it was long standing issue. But no more - fixed in 662ce7994e5afaeedb778981b24a0dc1e2ccceb4.

![image](https://user-images.githubusercontent.com/6976458/62536292-f130a380-b84d-11e9-9e3f-c07cab8a5bcc.png)

Though, gotta credit @CaptainD001 and his scripts for 3ds Max ( https://github.com/CaptainD001/M3_Import ) where he figured out correct way to import UVs on newer models. And I was able to use it as a reference.

**Comment by GetLocalPlayer** [comment]
Jesus Christ, thank you.
