### ISSUE TITLE
Poor performance when viewing m3 particles which have animation keyframes.

### ISSUE THREAD

**Issue by Solstice245** [Talv/m3addon#14]
The title about sums it up. When I use Blender, opening the particles tab often causes intense lag, and I finally found what the circumstances for it is. It only seems to happen if the particles have any key-frames in the animation which you are working in. (It only takes 1) I don't know any of the technical stuff behind all this but that is what I have observed. If a fix is possible it would be an appreciated one.

**Comment by Talv** [comment]
Yeah, that's something I've recently became aware of. Problem isn't exclusive to particles, but that's where it is most noticeable. Every panel that displays at least one animatable property is affected, but the more of them is displayed at once the worse it gets. Enormous models like VoidThrasher are lagging even on panels that have just a few animatable properties (like layers of an active material).

I'm not completely sure why performance gets so bad. But it has to do with how plugin manages animation tracks - every existing animation which animates some properties, regardless of what the property is adds up to the lag. Every keyframe adds up to the lag.. and so on.

Initially I've been thinking about just reducing the number of properties displayed in a single panel. To reduce the impact - i.e. splitting the particle panels to multiple ones. But it would be just a workaround, not really a fix. And it would likely barely help, because as shown here: https://streamable.com/49bce , problem is more global and a simple fix won't do the job.

I'll explore it further and see what can be done about it. But I'm afraid it might be deep in fundamentals of m3addon. And has existed since the beginning, but it gradually became worse as addon was receiving more and more features, and Blizzard models have been getting more complex.
(Completely fresh model with just one animation track and bunch of animated properties isn't affected).

Either way, I'll report back once I learn more. Because this is definitely something I want to fix.
