### ISSUE TITLE
Widowmaker Nova model issue

### ISSUE THREAD

**Issue by ThePlayer14** [Talv/m3addon#19]
When importing Widowmaker Nova's model into Blender with the addon, the import is not completely done, as some parts won't snap into their place after assigning animation to them with the PortraitAnims animation file.
The RequiredAnims animation file can't even be imported.

The log of importing the base m3 model:
https://pastebin.ubuntu.com/p/B8JZvtF6gP/

![anim](https://user-images.githubusercontent.com/24374531/71605560-02b27900-2b6a-11ea-8df6-0c043a42b8e6.png)
after adding the PortraitAnims file

Log: https://pastebin.ubuntu.com/p/4YcdhJqPZQ/

Trying to load RequiredAnims:
https://pastebin.ubuntu.com/p/Dv94Wgk4Th/

Note that the model has two different m3a files, but only one m3 file.
![image](https://user-images.githubusercontent.com/24374531/71605659-fa0e7280-2b6a-11ea-92cf-d3c3e8a6b126.png)

What could be the issue here?

**Comment by ThePlayer14** [comment]
The error when trying to load the RequiredAnims also appears when trying to import Deathwing's main .m3 file as well:
https://pastebin.ubuntu.com/p/Jkp8sQBVCN/

**Comment by Talv** [comment]
Errors from the log aren't strictly related to the actual problem I'm afraid.

> ERROR: Unknown section at offset 3499040 with tag=MADD version=2 repetitions=8 sectionLengthInBytes=1216 guessedUnusedSectionBytes=0 guessedBytesPerEntry=152.0

MADD section relates to new material type #12
Its role in the `m3a` is to animate properties of the referenced material from the base model. Ideally it should just be ignored, so the rest of the model can be processed.

> Loading rigid bodies
> ```
> Traceback (most recent call last):
>   File "C:\Users\Userx\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\m3addon-master\__init__.py", line 683, in handleRigidBodyBoneChange
>     selectCurrentRigidBodyBone(scene)
>   File "C:\Users\Userx\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\m3addon-master\__init__.py", line 688, in selectCurrentRigidBodyBone
>     selectBone(scene, rigidBody.boneName)
>   File "C:\Users\Userx\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\m3addon-master\__init__.py", line 825, in selectBone
>     b.select_set(False)
> AttributeError: 'Bone' object has no attribute 'select_set'
> ```

I'm actually aware about these as well, decided not touch it for the time being, since it only affects rigid bodies. It doesn't disturb import workline.

Primary problem is that `m3a`s require extra care in order to be properly applied to the model. It is possible to use the base from `m3`, remove imported armature, while preserving all other stuff. Then import `m3a` separately and attach new armature to the meshes.. yet, it's pretty much a workaround. The results are always *imperfect*, at least from my experience. Unless it's a very simple scenario where `m3a` has the same set of bones as base model.

In complex scenarios, like the one you've pointed out the `m3a` seems to contain extra set of bones. Which shouldn't be a problem on its own, but possibly it messes up some things down the line..
Unfortunately I'm not particularly familiar with how this stuff is currently coded and neither how it should be. I'll need some time to investigate it.

But basic idea would be to merge any imported `m3a` with already existing armature on the scene. Also, account for the fact that there might be multiple of `m3a` extending the same base model - as it appears to be very common thing in HotS.. and almost completely not existent in SC2.

btw. There's actually a script for merging the anims from `m3a` into the base model file https://github.com/Talv/m3addon/blob/7305ccbfc0b41e3cde666c651feb99e921174336/transferAnimations.py#L29 (written by flo who is now MIA). But I haven't been able to get it to work. Possibly it only worked on very first iterations of this anim file.

**Comment by neptuwunium** [comment]
In [my fork,](https://github.com/healingbrew/io_mesh_m3addon) I stubbed out `findNameAndMarkAsUsedLike` because it disrupts the asset flow in Heroes models. 

By doing this I can independently import the model and animation, and just edit the armature modifier on the model to use the m3a skeleton. Works for all models, including the newer ones as long as they have the same bone names.

My fork also doesn't crash with MADD structures, but it doesn't process material data for those models.

As mentioned this method doesn't work if the m3a defines more/less bones in the hierarchy, but this only applies to facial animations for Heroes of the Storm and can be fixed with some editing.

**Comment by ThePlayer14** [comment]
The forked version throws a different error:
https://pastebin.ubuntu.com/p/RsGrkDd6gc/

**Comment by Talv** [comment]
As of right now this is the intended way to import models from Storm:
https://user-images.githubusercontent.com/6976458/115144820-09128000-a04f-11eb-940e-17f8467a27cb.mp4
- first import m3a
- then m3, but without the rigging
- apply armature modifier from m3a to the imported meshes from m3
