### ISSUE TITLE
Tychus model’s

### ISSUE THREAD

**Issue by SheeldWall** [Talv/m3addon#4]
Tychus model’s are twisted and distorted.
![342](https://user-images.githubusercontent.com/24306412/47579960-82680680-d91b-11e8-8e52-799820aa3fbb.PNG)
![343](https://user-images.githubusercontent.com/24306412/47579972-898f1480-d91b-11e8-8033-e8261a820203.PNG)
![344](https://user-images.githubusercontent.com/24306412/47579984-96136d00-d91b-11e8-98c5-06991cb70825.PNG)
![345](https://user-images.githubusercontent.com/24306412/47580000-a4fa1f80-d91b-11e8-9845-c07ffa48bd26.PNG)

**Comment by AlleyV** [comment]
Pls if u can fix and Dark Templar family ( zeratul , preserver )

**Comment by Talv** [comment]
Unfortunately I don't know how to fix it. Multiple models are affected. From brief inspection it seems that it's an problem with bones transformations. In `pose mode` the model displays fine, however all animations are completely incorrect.

Someone more knowledgeable on the subject would have debug this, I don't have a clue...

**Comment by AlleyV** [comment]
Np, thank you very much also ^^

**Comment by AlleyV** [comment]
I have some news on this matter, with the new version of Art tools, when exporting the model it indicates the problems that the model has and it so happens that they are the ones that cause the model to be inverted, in this example zeratul.
https://i.imgur.com/uuo6cLH.png

**Comment by rocifier** [comment]
I figured out how to manually fix the negative scale issue. Look through every bone in the armature and find the ones which have negative scale on the m3 bone binding, usually (-1,-1,-1). Invert the vector, in that case to (1,1,1) and then invert the scale in blender (usually so that it will become negative. the end result of this will look like below, I'm using War3HD_Gate.m3 because its a much simpler model):
![image](https://user-images.githubusercontent.com/1772304/183586518-7bc5ab0e-0a30-40bb-9de0-74f77a32d449.png)
However a new problem is presented in both blender (when enabling back-face culling) and when exporting/importing into sc2. The negative scales invert the mesh normals:
![image](https://user-images.githubusercontent.com/1772304/183586765-1aa5bab3-41d1-4f9c-9ad0-7254151cddde.png)
This is basically a semi-documented behavior of using blender in a way which it is not supposed to be used. 
The easiest solution in this situation which I found to fix it is to go back to Model workspace, tab into the mesh in question, select the vertex groups which look inside-out, and then press Alt+N and flip:
![image](https://user-images.githubusercontent.com/1772304/183588192-3817181d-decc-4585-907f-edb62bb71369.png)
Worked:
![image](https://user-images.githubusercontent.com/1772304/183588277-2c863a45-153a-462c-ba27-489b80f49c59.png)
Edit: Tested the workflow on the dark templar, worked (just trust me that the animation matches the original one inside the cutscene viewer). There was one other thing I noticed only on this model, a couple of the inverted bones also had positions which spaced them erroneously apart from their parent bone. Zeroing all the locations of each bone was the solution to properly clean this up. No rotations were affected.
![image](https://user-images.githubusercontent.com/1772304/183596650-1cebd91c-8a6f-44e1-933e-7c354b5453a6.png)
